export const fieldMapping: Record<
  string,
  { fields: string[]; labels: Record<string, string> }
> = {
  Language: {
    fields: ["inclusive_language_required", "plain_language_summary_required"],
    labels: {
      InclusiveLanguage: "Inclusive Language",
      PlainLanguageSummary: "Plain Language Summary",
    },
  },
  Reference: {
    fields: [
      "reference_age_check",
      "max_reference_age",
      "percentage_reference_below_max_age",
      "abstract_citation_limitation",
      "min_reference_count",
      "max_reference_count",
      "inline_citations_required",
      "self_citation_check",
      "reference_style_limitation",
      "reference_style",
    ],
    labels: {
      ReferenceAgeCheck: "Reference Age Check",
      MaxReferenceAge: "Maximum Reference Age",
      PercentageReferenceBelowMaxAge: "Reference Below Max Age",
      CitationsInAbstract: "Citations in Abstract",
      MinReferenceCount: "Minimum Reference Count",
      MaxReferenceCount: "Maximum Reference Count",
      InlineCitationsRequired: "Inline Citation",
      SelfCitationCheck: "Self Citation Check",
      ReferenceStyleLimitation: "Reference Style Limitation",
      ReferenceStyle: "Reference Style",
    },
  },
  Structure: {
    fields: [
      "manuscript_structure_required",
      "manuscript_structure",
      "abstract_structure_required",
      "abstract_structure",
      "font_style_limitation",
      "font_style",
      "font_size",
      "manuscript_file_format_limitation",
      "manuscript_file_format",
    ],
    labels: {
      ManuscriptStructure: "Manuscript Structure",
      ManuscriptStructureFormat: "Manuscript Structure Format",
      AbstractStructure: "Abstract Structure",
      AbstractStructureFormat: "Abstract Structure Format",
      FontStyleRequired: "Font Style Required",
      ManuscriptFontStyle: "Manuscript Font Style",
      ManuscriptFontSize: "Manuscript Font Size",
      ManuscriptFileFormatLimitation: "Manuscript Format Required",
      ManuscriptFileFormat: "Manuscript File Format",
    },
  },
  Counts: {
    fields: [
      "min_abstract_words",
      "max_abstract_words",
      "min_manuscript_words",
      "max_manuscript_words",
      "word_count_includes_reference",
      "min_title_words",
      "max_title_words",
      "excessive_branding_check",
    ],
    labels: {
      MinimumAbstractLength: "Minimum Abstract Length",
      MaximumAbstractLength: "Maximum Abstract Length",
      MinimumManuscriptLength: "Minimum Manuscript Length",
      MaximumManuscriptLength: "Maximum Manuscript Length",
      ManuscriptLengthIncludesReferences:
        "Manuscript Length Includes References",
      MinimumTitleLength: "Minimum Title Length",
      MaximumTitleLength: "Maximum Title Length",
      ExcessiveBrandingCheck: "Excessive Branding Check",
    },
  },
  FiguresAndTables: {
    fields: [
      "figure_legend_required",
      "max_figure_legend_words",
      "max_figure_count",
      "table_legend_required",
      "max_table_count",
      "max_table_legend_words",
    ],
    labels: {
      FigureLegends: "Figure Legends",
      MaxWordsInFigureLegends: "Maximum Words in Figure Legends",
      MaxFiguresAllowed: "Maximum Figures Allowed",
      TableLegends: "Table Legends",
      MaxTablesAllowed: "Maximum Tables Allowed",
      MaxWordsInTableLegends: "Maximum Words in Table Legends",
    },
  },
  Disclosures: {
    fields: [
      "author_contribution_statement_required",
      "COI_statement_required",
      "data_access_statement_required",
      "ethics_statement_required",
      "funding_statement_required",
      "copyright_statement_required",
      "word_count_statement_required",
    ],
    labels: {
      AuthorContributionStatement: "Author Contribution Statement",
      ConflictOfInterestStatement: "Conflict of Interest Statement",
      DataAccessStatement: "Data Access Statement",
      EthicsStatement: "Ethics Statement",
      FundingStatement: "Funding Statement",
      CopyrightStatement: "Copyright Statement",
      ManuscriptLengthStatement: "Manuscript Length Statement",
    },
  },
  MetaData: {
    fields: [
      "abstract_required",
      "author_list_required",
      "max_authors_count",
      "title_word_limitation",
      "manuscript_word_limitation",
      "corresponding_author_email_required",
      "keywords_required",
      "min_keyword_count",
      "max_keyword_count",
    ],
    labels: {
      Abstract: "Abstract",
      AuthorsList: "Authors List",
      MaxAuthorsAllowed: "Maximum Authors Allowed",
      TitleWordLimitation: "Limited Title Length",
      ManuscriptWordLimitation: "Limited Manuscript Length",
      CorrespondingAuthorsEmailAddress: "Corresponding Author's Email Address",
      KeywordsList: "Keywords List",
      MinKeywordsAllowed: "Minimum Keywords Allowed",
      MaxKeywordsAllowed: "Maximum Keywords Allowed",
    },
  },
};
