export const fieldMapping: Record<
  string,
  { fields: string[]; labels: Record<string, string> }
> = {
  Language: {
    fields: ["inclusive_language_required", "plain_language_summary_required"],
    labels: {
      InclusiveLanguage: "Inclusive Language",
      PlainLanguageSummary: "Plain Language Summary",
    },
  },
  Reference: {
    fields: [
      "reference_age_check",
      "max_reference_age",
      "percentage_reference_below_max_age",
      "abstract_citation_limitation",
      "min_reference_count",
      "inline_citations_required",
      "self_citation_check",
      "reference_style_limitation",
      "reference_style",
    ],
    labels: {
      ReferenceAgeCheck: "Reference Age Check",
      MaxReferenceAge: "Maximum Reference Age",
      PercentageReferenceBelowMaxAge: "Reference Below Max Age",
      CitationsInAbstract: "Citations in Abstract",
      MinReferenceCount: "Reference Count",
      InlineCitationsRequired: "Inline Citation",
      SelfCitationCheck: "Self Citation Check",
      ReferenceStyleLimitation: "Reference Style Limitation",
      ReferenceStyle: "Reference Style",
    },
  },
  Structure: {
    fields: [
      "manuscript_structure_required",
      "manuscript_structure",
      "abstract_structure_required",
      "abstract_structure",
      "font_style_limitation",
      "font_style",
      "font_size",
      "manuscript_file_format_limitation",
      "manuscript_file_format",
    ],
    labels: {
      ManuscriptStructure: "Manuscript Structure",
      ManuscriptStructureFormat: "Manuscript Structure Format",
      AbstractStructure: "Abstract Structure",
      AbstractStructureFormat: "Abstract Structure Format",
      ManuscriptFontStyle: "Manuscript Font Style",
      ManuscriptFontSize: "Manuscript Font Size",
      ManuscriptFileFormat: "Manuscript File Format",
    },
  },
  Counts: {
    fields: [
      "abstract_required",
      "max_abstract_words",
      "max_manuscript_words",
      "word_count_includes_reference",
      "max_title_words",
      "excessive_branding_check",
    ],
    labels: {
      AbstractLength: "Abstract Length",
      ManuscriptLength: "Manuscript Length",
      ManuscriptLengthIncludesReferences:
        "Manuscript Length Includes References",
      TitleLength: "Title Length",
      ExcessiveBrandingCheck: "Excessive Branding Check",
    },
  },
  FiguresAndTables: {
    fields: [
      "figure_legend_required",
      "max_figure_legend_words",
      "max_figure_count",
      "table_legend_required",
      "max_table_count",
      "max_table_legend_words",
    ],
    labels: {
      FigureLegends: "Figure Legends",
      MaxWordsInFigureLegends: "Maximum Words in Figure Legends",
      MaxFiguresAllowed: "Maximum Figures Allowed",
      TableLegends: "Table Legends",
      MaxTablesAllowed: "Maximum Tables Allowed",
      MaxWordsInTableLegends: "Maximum Words in Table Legends",
    },
  },
  Disclosures: {
    fields: [
      "author_contribution_statement_required",
      "COI_statement_required",
      "data_access_statement_required",
      "ethics_statement_required",
      "funding_statement_required",
      "copyright_statement_required",
      "manuscript_word_limitation",
    ],
    labels: {
      AuthorContributionStatement: "Author Contribution Statement",
      ConflictOfInterestStatement: "Conflict of Interest Statement",
      DataAccessStatement: "Data Access Statement",
      EthicsStatement: "Ethics Statement",
      FundingStatement: "Funding Statement",
      CopyrightStatement: "Copyright Statement",
      ManuscriptWordLimitation: "Manuscript Word Limitation",
    },
  },
  MetaData: {
    fields: [
      "abstract_required",
      "abstract_structure_required",
      "author_list_required",
      "max_authors_count",
      "corresponding_author_email_required",
      "keywords_required",
      "min_keyword_count",
      "max_keyword_count",
    ],
    labels: {
      Abstract: "Abstract",
      UnstructuredAbstract: "Unstructured Abstract",
      AuthorsList: "Authors List",
      MaxAuthorsAllowed: "Maximum Authors Allowed",
      CorrespondingAuthorsEmailAddress: "Corresponding Author's Email Address",
      KeywordsList: "Keywords List",
      MinKeywordsAllowed: "Minimum Keywords Allowed",
      MaxKeywordsAllowed: "Maximum Keywords Allowed",
    },
  },
};
